"""Game configuration constants."""

GAME_TITLE = 'LAN PONG'
FPS = 30
WINDOW_DIMENSIONS = (600, 400)

# Pads
PAD_SIZE = (20, 120)
LEFT_PAD_POSITION = (20, (WINDOW_DIMENSIONS[1] // 2) - (PAD_SIZE[1] // 2))
RIGHT_PAD_POSITION = (
    WINDOW_DIMENSIONS[0] - PAD_SIZE[0] - 20,
    (WINDOW_DIMENSIONS[1] // 2) - (PAD_SIZE[1] // 2)
)
LEFT_PAD_MOVEMENT_SPEED = 10  # in pixels per frame
RIGHT_PAD_MOVEMENT_SPEED = 5

# Ball
BALL_POSITION = (
    WINDOW_DIMENSIONS[0] // 2,
    WINDOW_DIMENSIONS[1] // 2
)
BALL_RADIUS = 16
BALL_MOVEMENT_SPEED = (10, 0)
BALL_MOVEMENT_SPEED_DELTA = 5
